### PR TITLE
139 - Support running as a pod in cluster

### LINKED ISSUE #139: Support In-cluster configuration
It would be great if this can work with in-cluster configuration. This means, it will not have a `~/.kube/config` file but will have direct access to API server as the pod will be running inside the cluster to be managed.

Currently (As of 9 May 2025) this does not work and fails by generating API server URL like `https://undefined:undefined/api/v1/...`

### PR DESCRIPTION
**Pull request by ajit-pendse**
Resolves #139.

### CODE REVIEW

**Comment by rr-paras-patel** [comment]
can you try this on your local one more time? we just merged one jumbo PR.

**Comment by ajit-pendse** [comment]
Integrated latest changes in the PR. Test cases for kubernetes-manager pass. Also tested on a live kubernetes cluster.

File: src/utils/kubernetes-manager.ts [hunk 1]
```diff
@@ -12,27 +13,48 @@ export class KubernetesManager {
...
   constructor() {
     this.kc = new k8s.KubeConfig();
-    this.kc.loadFromDefault();
+    if (this.isRunningInCluster()) {
+      console.log("Running inside a Kubernetes cluster");
+      this.kc.loadFromCluster();
+    } else {
+      console.log("Loading default kube config file");
+      this.kc.loadFromDefault();
+    }
```
Comment (Flux159) [inline src/utils/kubernetes-manager.ts:22]:
```suggestion
    if (this.isRunningInCluster()) {
      this.kc.loadFromCluster();
    } else {
      this.kc.loadFromDefault();
    }
```

I think some clients had issues if you put stdout that isn't valid jsonrpc

**Review by Flux159 — COMMENTED** [review]
LGTM, just remove the console logs

**Comment by Flux159** [comment]
Oh I have a separate question - since we moved to using kubectl cli for a lot of commands, does kubectl also automatically look at the token in `/var/run/secrets/kubernetes.io/serviceaccount/token` if you run from a cluster & have it installed in that container? 

Right now this code change just adjusts the node-client, but if kubectl in the container needs some configuration change then that won't be done / server will probably error out.

**Comment by ajit-pendse** [comment]
Yes - `kubectl` looks for the same file and supports automatic detection for in-cluster use cases. Ref - https://kubernetes.io/docs/reference/kubectl/#in-cluster-authentication-and-namespace-overrides

File: src/utils/kubernetes-manager.ts (hunk 1 above)
Comment (ajit-pendse) [reply src/utils/kubernetes-manager.ts]: Updated to remove console.log statements.

**Review by Flux159 — APPROVED** [review]
Code LGTM & tests pass

**Comment by Flux159** [comment]
Merged this in & it should be available in version 2.1.0 when it's published to NPM.

@ajit-pendse - Since we have kubectl installed in the [docker container for kubernetes-mcp-server](https://github.com/Flux159/mcp-server-kubernetes/blob/v2.1.0/Dockerfile), that means that we could just tell people to run the that container inside of their cluster now right? 

Since it's using a token inside of the container, in theory it wouldn't need the aws or gcp auth plugins in order to authenticate inside of EKS or GKE if it was run inside of the cluster?

**Comment by ajit-pendse** [comment]
> Merged this in & it should be available in version 2.1.0 when it's published to NPM.
> 
> @ajit-pendse - Since we have kubectl installed in the [docker container for kubernetes-mcp-server](https://github.com/Flux159/mcp-server-kubernetes/blob/v2.1.0/Dockerfile), that means that we could just tell people to run the that container inside of their cluster now right?
> 
> Since it's using a token inside of the container, in theory it wouldn't need the aws or gcp auth plugins in order to authenticate inside of EKS or GKE if it was run inside of the cluster?

Yes, if this code is running inside a pod in the cluster, no additional authentication details or plugins are needed. 

However, for RBAC enabled clusters, the identity used by the pod (be default, a service account named `default` in the same namespace  as the pod - but there are multiple ways to assign identity to a running pod) will need appropriate access provided to the resources to be managed by the mcp server. While this is out of scope for the mcp server, it would be a good idea to mention it in documentation.

Ref. - https://kubernetes.io/docs/reference/access-authn-authz/rbac/#role-and-clusterrole

**Comment by Flux159** [comment]
> However, for RBAC enabled clusters, the identity used by the pod (be default, a service account named default in the same namespace as the pod - but there are multiple ways to assign identity to a running pod) will need appropriate access provided to the resources to be managed by the mcp server. While this is out of scope for the mcp server, it would be a good idea to mention it in documentation.

Ah okay, so the service account defined for a deployment/container for something like GKE would need permissions to administer the GKE cluster to be able to use all the kubectl commands - this makes sense. Will add to the readme in a followup. I think this also makes the docker container a lot more useful, so probably makes sense to add to the readme now.
